server:
  port: 8888
  tomcat:
    max-http-post-size: -1
spring:
  datasource:
    url: jdbc:mysql://cdb-a65jevgj.gz.tencentcdb.com:10008/visualization
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gisv
    password: gyg123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    static-path-pattern: /static/**
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace  #配置该项才能显示SQL参数
    com.sun.vue-background: debug